// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: flat.proto

#include "flat.pb.h"
#include "flat.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace test {

static const char* Test_method_names[] = {
  "/test.Test/Echo",
};

std::unique_ptr< Test::Stub> Test::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Test::Stub> stub(new Test::Stub(channel, options));
  return stub;
}

Test::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Echo_(Test_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Test::Stub::Echo(::grpc::ClientContext* context, const ::test::FlatLogFileFlushChunkRequestPB& request, ::test::FlatLogFileFlushChunkResponsePB* response) {
  return ::grpc::internal::BlockingUnaryCall< ::test::FlatLogFileFlushChunkRequestPB, ::test::FlatLogFileFlushChunkResponsePB, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Echo_, context, request, response);
}

void Test::Stub::async::Echo(::grpc::ClientContext* context, const ::test::FlatLogFileFlushChunkRequestPB* request, ::test::FlatLogFileFlushChunkResponsePB* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::test::FlatLogFileFlushChunkRequestPB, ::test::FlatLogFileFlushChunkResponsePB, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Echo_, context, request, response, std::move(f));
}

void Test::Stub::async::Echo(::grpc::ClientContext* context, const ::test::FlatLogFileFlushChunkRequestPB* request, ::test::FlatLogFileFlushChunkResponsePB* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Echo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::test::FlatLogFileFlushChunkResponsePB>* Test::Stub::PrepareAsyncEchoRaw(::grpc::ClientContext* context, const ::test::FlatLogFileFlushChunkRequestPB& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::test::FlatLogFileFlushChunkResponsePB, ::test::FlatLogFileFlushChunkRequestPB, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Echo_, context, request);
}

::grpc::ClientAsyncResponseReader< ::test::FlatLogFileFlushChunkResponsePB>* Test::Stub::AsyncEchoRaw(::grpc::ClientContext* context, const ::test::FlatLogFileFlushChunkRequestPB& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncEchoRaw(context, request, cq);
  result->StartCall();
  return result;
}

Test::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Test_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Test::Service, ::test::FlatLogFileFlushChunkRequestPB, ::test::FlatLogFileFlushChunkResponsePB, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Test::Service* service,
             ::grpc::ServerContext* ctx,
             const ::test::FlatLogFileFlushChunkRequestPB* req,
             ::test::FlatLogFileFlushChunkResponsePB* resp) {
               return service->Echo(ctx, req, resp);
             }, this)));
}

Test::Service::~Service() {
}

::grpc::Status Test::Service::Echo(::grpc::ServerContext* context, const ::test::FlatLogFileFlushChunkRequestPB* request, ::test::FlatLogFileFlushChunkResponsePB* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace test

